name: Build Electron App and Generate MSI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can change this to your version

    - name: Install dependencies
      run: |
        npm ci

    - name: Build Electron App
      run: |
        npm run dist  # or your custom build script

    - name: Upload MSI as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: msi-installer
        path: dist/*.msi  # Adjust this path if your MSI is in a different directory

